### ISSUE TITLE
Correggere URL pagina "sottoscrivi"

### ISSUE THREAD

**Issue by aborruso** [openpuglia/facciamopolitica#1]
In attesa dei domini di terzo livello, correggere gli URL indicati qui http://opendatabari.github.io/facciamopolitica/subscribe.html

Gli URL errati sono qui https://github.com/opendatabari/facciamopolitica/blob/gh-pages/subscribe.html#L111-L114

**Comment by pietroblu** [comment]
Sistemerò non appena @Mikelantonio attiverà il dominio di terzo livello http://iovotopendata.openpuglia.org

**Comment by aborruso** [comment]
In questi giorni perché non inserisci l'URL attuale?

---

Scusami per la brevità, ti sto scrivendo dal cellulare.

website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E EPSG:4326

**Comment by pietroblu** [comment]
ok, va bene ;)

**Comment by pietroblu** [comment]
fatto, il provvisorio è operativo
